/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_storj_uplink(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_storj_uplink(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_storj_uplink(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


	/* Includes the header in the wrapper code */
	#include "uplink_definitions.h"
	#include "storj_uplink.h"



char* get_storj_version(){
	return "v1.0.2";
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG__GoString__p_set___(void * jarg1, char * jarg2) {
  _GoString_ *arg1 = (_GoString_ *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (_GoString_ *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->p = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->p, (const char *)arg2);
    } else {
      arg1->p = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG__GoString__p_get___(void * jarg1) {
  char * jresult ;
  _GoString_ *arg1 = (_GoString_ *) 0 ;
  char *result = 0 ;
  
  arg1 = (_GoString_ *)jarg1; 
  result = (char *) ((arg1)->p);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG__GoString__n_set___(void * jarg1, void * jarg2) {
  _GoString_ *arg1 = (_GoString_ *) 0 ;
  ptrdiff_t arg2 ;
  ptrdiff_t *argp2 ;
  
  arg1 = (_GoString_ *)jarg1; 
  argp2 = (ptrdiff_t *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null ptrdiff_t", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->n = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG__GoString__n_get___(void * jarg1) {
  void * jresult ;
  _GoString_ *arg1 = (_GoString_ *) 0 ;
  ptrdiff_t result;
  
  arg1 = (_GoString_ *)jarg1; 
  result =  ((arg1)->n);
  {
    ptrdiff_t * resultptr = (ptrdiff_t *) malloc(sizeof(ptrdiff_t));
    memmove(resultptr, &result, sizeof(ptrdiff_t));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new__GoString____() {
  void * jresult ;
  _GoString_ *result = 0 ;
  
  result = (_GoString_ *)calloc(1, sizeof(_GoString_));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete__GoString____(void * jarg1) {
  _GoString_ *arg1 = (_GoString_ *) 0 ;
  
  arg1 = (_GoString_ *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_GoInterface_t_set___(void * jarg1, void * jarg2) {
  GoInterface *arg1 = (GoInterface *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = (GoInterface *)jarg1; 
  arg2 = (void *)jarg2; 
  if (arg1) (arg1)->t = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_GoInterface_t_get___(void * jarg1) {
  void * jresult ;
  GoInterface *arg1 = (GoInterface *) 0 ;
  void *result = 0 ;
  
  arg1 = (GoInterface *)jarg1; 
  result = (void *) ((arg1)->t);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_GoInterface_v_set___(void * jarg1, void * jarg2) {
  GoInterface *arg1 = (GoInterface *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = (GoInterface *)jarg1; 
  arg2 = (void *)jarg2; 
  if (arg1) (arg1)->v = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_GoInterface_v_get___(void * jarg1) {
  void * jresult ;
  GoInterface *arg1 = (GoInterface *) 0 ;
  void *result = 0 ;
  
  arg1 = (GoInterface *)jarg1; 
  result = (void *) ((arg1)->v);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_GoInterface___() {
  void * jresult ;
  GoInterface *result = 0 ;
  
  result = (GoInterface *)calloc(1, sizeof(GoInterface));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_GoInterface___(void * jarg1) {
  GoInterface *arg1 = (GoInterface *) 0 ;
  
  arg1 = (GoInterface *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_GoSlice_data_set___(void * jarg1, void * jarg2) {
  GoSlice *arg1 = (GoSlice *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = (GoSlice *)jarg1; 
  arg2 = (void *)jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_GoSlice_data_get___(void * jarg1) {
  void * jresult ;
  GoSlice *arg1 = (GoSlice *) 0 ;
  void *result = 0 ;
  
  arg1 = (GoSlice *)jarg1; 
  result = (void *) ((arg1)->data);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_GoSlice_len_set___(void * jarg1, long long jarg2) {
  GoSlice *arg1 = (GoSlice *) 0 ;
  GoInt arg2 ;
  
  arg1 = (GoSlice *)jarg1; 
  arg2 = (GoInt)jarg2; 
  if (arg1) (arg1)->len = arg2;
}


SWIGEXPORT long long SWIGSTDCALL CSharp_uplinkfSWIG_GoSlice_len_get___(void * jarg1) {
  long long jresult ;
  GoSlice *arg1 = (GoSlice *) 0 ;
  GoInt result;
  
  arg1 = (GoSlice *)jarg1; 
  result = (GoInt) ((arg1)->len);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_GoSlice_cap_set___(void * jarg1, long long jarg2) {
  GoSlice *arg1 = (GoSlice *) 0 ;
  GoInt arg2 ;
  
  arg1 = (GoSlice *)jarg1; 
  arg2 = (GoInt)jarg2; 
  if (arg1) (arg1)->cap = arg2;
}


SWIGEXPORT long long SWIGSTDCALL CSharp_uplinkfSWIG_GoSlice_cap_get___(void * jarg1) {
  long long jresult ;
  GoSlice *arg1 = (GoSlice *) 0 ;
  GoInt result;
  
  arg1 = (GoSlice *)jarg1; 
  result = (GoInt) ((arg1)->cap);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_GoSlice___() {
  void * jresult ;
  GoSlice *result = 0 ;
  
  result = (GoSlice *)calloc(1, sizeof(GoSlice));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_GoSlice___(void * jarg1) {
  GoSlice *arg1 = (GoSlice *) 0 ;
  
  arg1 = (GoSlice *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_parse_access___(char * jarg1) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  AccessResult result;
  
  arg1 = (char *)jarg1; 
  result = parse_access(arg1);
  {
    AccessResult * resultptr = (AccessResult *) malloc(sizeof(AccessResult));
    memmove(resultptr, &result, sizeof(AccessResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_request_access_with_passphrase___(char * jarg1, char * jarg2, char * jarg3) {
  void * jresult ;
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  AccessResult result;
  
  arg1 = (char *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  result = request_access_with_passphrase(arg1,arg2,arg3);
  {
    AccessResult * resultptr = (AccessResult *) malloc(sizeof(AccessResult));
    memmove(resultptr, &result, sizeof(AccessResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_access_serialize___(void * jarg1) {
  void * jresult ;
  Access *arg1 = (Access *) 0 ;
  StringResult result;
  
  arg1 = (Access *)jarg1; 
  result = access_serialize(arg1);
  {
    StringResult * resultptr = (StringResult *) malloc(sizeof(StringResult));
    memmove(resultptr, &result, sizeof(StringResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_access_share___(void * jarg1, void * jarg2, void * jarg3, long long jarg4) {
  void * jresult ;
  Access *arg1 = (Access *) 0 ;
  Permission arg2 ;
  SharePrefix *arg3 = (SharePrefix *) 0 ;
  GoInt arg4 ;
  Permission *argp2 ;
  AccessResult result;
  
  arg1 = (Access *)jarg1; 
  argp2 = (Permission *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Permission", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (SharePrefix *)jarg3; 
  arg4 = (GoInt)jarg4; 
  result = access_share(arg1,arg2,arg3,arg4);
  {
    AccessResult * resultptr = (AccessResult *) malloc(sizeof(AccessResult));
    memmove(resultptr, &result, sizeof(AccessResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_string_result___(void * jarg1) {
  StringResult arg1 ;
  StringResult *argp1 ;
  
  argp1 = (StringResult *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null StringResult", 0);
    return ;
  }
  arg1 = *argp1; 
  free_string_result(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_access_result___(void * jarg1) {
  AccessResult arg1 ;
  AccessResult *argp1 ;
  
  argp1 = (AccessResult *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null AccessResult", 0);
    return ;
  }
  arg1 = *argp1; 
  free_access_result(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_stat_bucket___(void * jarg1, char * jarg2) {
  void * jresult ;
  Project *arg1 = (Project *) 0 ;
  char *arg2 = (char *) 0 ;
  BucketResult result;
  
  arg1 = (Project *)jarg1; 
  arg2 = (char *)jarg2; 
  result = stat_bucket(arg1,arg2);
  {
    BucketResult * resultptr = (BucketResult *) malloc(sizeof(BucketResult));
    memmove(resultptr, &result, sizeof(BucketResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_create_bucket___(void * jarg1, char * jarg2) {
  void * jresult ;
  Project *arg1 = (Project *) 0 ;
  char *arg2 = (char *) 0 ;
  BucketResult result;
  
  arg1 = (Project *)jarg1; 
  arg2 = (char *)jarg2; 
  result = create_bucket(arg1,arg2);
  {
    BucketResult * resultptr = (BucketResult *) malloc(sizeof(BucketResult));
    memmove(resultptr, &result, sizeof(BucketResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_ensure_bucket___(void * jarg1, char * jarg2) {
  void * jresult ;
  Project *arg1 = (Project *) 0 ;
  char *arg2 = (char *) 0 ;
  BucketResult result;
  
  arg1 = (Project *)jarg1; 
  arg2 = (char *)jarg2; 
  result = ensure_bucket(arg1,arg2);
  {
    BucketResult * resultptr = (BucketResult *) malloc(sizeof(BucketResult));
    memmove(resultptr, &result, sizeof(BucketResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_delete_bucket___(void * jarg1, char * jarg2) {
  void * jresult ;
  Project *arg1 = (Project *) 0 ;
  char *arg2 = (char *) 0 ;
  BucketResult result;
  
  arg1 = (Project *)jarg1; 
  arg2 = (char *)jarg2; 
  result = delete_bucket(arg1,arg2);
  {
    BucketResult * resultptr = (BucketResult *) malloc(sizeof(BucketResult));
    memmove(resultptr, &result, sizeof(BucketResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_bucket_result___(void * jarg1) {
  BucketResult arg1 ;
  BucketResult *argp1 ;
  
  argp1 = (BucketResult *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null BucketResult", 0);
    return ;
  }
  arg1 = *argp1; 
  free_bucket_result(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_bucket___(void * jarg1) {
  Bucket *arg1 = (Bucket *) 0 ;
  
  arg1 = (Bucket *)jarg1; 
  free_bucket(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_list_buckets___(void * jarg1, void * jarg2) {
  void * jresult ;
  Project *arg1 = (Project *) 0 ;
  ListBucketsOptions *arg2 = (ListBucketsOptions *) 0 ;
  BucketIterator *result = 0 ;
  
  arg1 = (Project *)jarg1; 
  arg2 = (ListBucketsOptions *)jarg2; 
  result = (BucketIterator *)list_buckets(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT _Bool SWIGSTDCALL CSharp_uplinkfSWIG_bucket_iterator_next___(void * jarg1) {
  _Bool jresult ;
  BucketIterator *arg1 = (BucketIterator *) 0 ;
  _Bool result;
  
  arg1 = (BucketIterator *)jarg1; 
  result = bucket_iterator_next(arg1);
  jresult = (_Bool)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_bucket_iterator_err___(void * jarg1) {
  void * jresult ;
  BucketIterator *arg1 = (BucketIterator *) 0 ;
  Error *result = 0 ;
  
  arg1 = (BucketIterator *)jarg1; 
  result = (Error *)bucket_iterator_err(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_bucket_iterator_item___(void * jarg1) {
  void * jresult ;
  BucketIterator *arg1 = (BucketIterator *) 0 ;
  Bucket *result = 0 ;
  
  arg1 = (BucketIterator *)jarg1; 
  result = (Bucket *)bucket_iterator_item(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_bucket_iterator___(void * jarg1) {
  BucketIterator *arg1 = (BucketIterator *) 0 ;
  
  arg1 = (BucketIterator *)jarg1; 
  free_bucket_iterator(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_config_request_access_with_passphrase___(void * jarg1, char * jarg2, char * jarg3, char * jarg4) {
  void * jresult ;
  Config arg1 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  Config *argp1 ;
  AccessResult result;
  
  argp1 = (Config *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Config", 0);
    return 0;
  }
  arg1 = *argp1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  arg4 = (char *)jarg4; 
  result = config_request_access_with_passphrase(arg1,arg2,arg3,arg4);
  {
    AccessResult * resultptr = (AccessResult *) malloc(sizeof(AccessResult));
    memmove(resultptr, &result, sizeof(AccessResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_config_open_project___(void * jarg1, void * jarg2) {
  void * jresult ;
  Config arg1 ;
  Access *arg2 = (Access *) 0 ;
  Config *argp1 ;
  ProjectResult result;
  
  argp1 = (Config *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Config", 0);
    return 0;
  }
  arg1 = *argp1; 
  arg2 = (Access *)jarg2; 
  result = config_open_project(arg1,arg2);
  {
    ProjectResult * resultptr = (ProjectResult *) malloc(sizeof(ProjectResult));
    memmove(resultptr, &result, sizeof(ProjectResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_prepare_custommetadata___() {
  prepare_custommetadata();
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_append_custommetadata___(char * jarg1, char * jarg2) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (char *)jarg2; 
  append_custommetadata(arg1,arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_upload_set_custom_metadata2___(void * jarg1) {
  void * jresult ;
  Upload *arg1 = (Upload *) 0 ;
  Error *result = 0 ;
  
  arg1 = (Upload *)jarg1; 
  result = (Error *)upload_set_custom_metadata2(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_prepare_get_custommetadata___(void * jarg1) {
  Object *arg1 = (Object *) 0 ;
  
  arg1 = (Object *)jarg1; 
  prepare_get_custommetadata(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_get_next_custommetadata___() {
  void * jresult ;
  CustomMetadataEntry result;
  
  result = get_next_custommetadata();
  {
    CustomMetadataEntry * resultptr = (CustomMetadataEntry *) malloc(sizeof(CustomMetadataEntry));
    memmove(resultptr, &result, sizeof(CustomMetadataEntry));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_download_object___(void * jarg1, char * jarg2, char * jarg3, void * jarg4) {
  void * jresult ;
  Project *arg1 = (Project *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  DownloadOptions *arg4 = (DownloadOptions *) 0 ;
  DownloadResult result;
  
  arg1 = (Project *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  arg4 = (DownloadOptions *)jarg4; 
  result = download_object(arg1,arg2,arg3,arg4);
  {
    DownloadResult * resultptr = (DownloadResult *) malloc(sizeof(DownloadResult));
    memmove(resultptr, &result, sizeof(DownloadResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_download_read___(void * jarg1, void * jarg2, unsigned long jarg3) {
  void * jresult ;
  Download *arg1 = (Download *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  ReadResult result;
  
  arg1 = (Download *)jarg1; 
  arg2 = (void *)jarg2; 
  arg3 = (size_t)jarg3; 
  result = download_read(arg1,arg2,arg3);
  {
    ReadResult * resultptr = (ReadResult *) malloc(sizeof(ReadResult));
    memmove(resultptr, &result, sizeof(ReadResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_download_info___(void * jarg1) {
  void * jresult ;
  Download *arg1 = (Download *) 0 ;
  ObjectResult result;
  
  arg1 = (Download *)jarg1; 
  result = download_info(arg1);
  {
    ObjectResult * resultptr = (ObjectResult *) malloc(sizeof(ObjectResult));
    memmove(resultptr, &result, sizeof(ObjectResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_read_result___(void * jarg1) {
  ReadResult arg1 ;
  ReadResult *argp1 ;
  
  argp1 = (ReadResult *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null ReadResult", 0);
    return ;
  }
  arg1 = *argp1; 
  free_read_result(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_close_download___(void * jarg1) {
  void * jresult ;
  Download *arg1 = (Download *) 0 ;
  Error *result = 0 ;
  
  arg1 = (Download *)jarg1; 
  result = (Error *)close_download(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_download_result___(void * jarg1) {
  DownloadResult arg1 ;
  DownloadResult *argp1 ;
  
  argp1 = (DownloadResult *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null DownloadResult", 0);
    return ;
  }
  arg1 = *argp1; 
  free_download_result(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_error___(void * jarg1) {
  Error *arg1 = (Error *) 0 ;
  
  arg1 = (Error *)jarg1; 
  free_error(arg1);
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_uplinkfSWIG_internal_UniverseIsEmpty___() {
  unsigned char jresult ;
  GoUint8 result;
  
  result = (GoUint8)internal_UniverseIsEmpty();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_stat_object___(void * jarg1, char * jarg2, char * jarg3) {
  void * jresult ;
  Project *arg1 = (Project *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  ObjectResult result;
  
  arg1 = (Project *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  result = stat_object(arg1,arg2,arg3);
  {
    ObjectResult * resultptr = (ObjectResult *) malloc(sizeof(ObjectResult));
    memmove(resultptr, &result, sizeof(ObjectResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_delete_object___(void * jarg1, char * jarg2, char * jarg3) {
  void * jresult ;
  Project *arg1 = (Project *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  ObjectResult result;
  
  arg1 = (Project *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  result = delete_object(arg1,arg2,arg3);
  {
    ObjectResult * resultptr = (ObjectResult *) malloc(sizeof(ObjectResult));
    memmove(resultptr, &result, sizeof(ObjectResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_object_result___(void * jarg1) {
  ObjectResult arg1 ;
  ObjectResult *argp1 ;
  
  argp1 = (ObjectResult *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null ObjectResult", 0);
    return ;
  }
  arg1 = *argp1; 
  free_object_result(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_object___(void * jarg1) {
  Object *arg1 = (Object *) 0 ;
  
  arg1 = (Object *)jarg1; 
  free_object(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_list_objects___(void * jarg1, char * jarg2, void * jarg3) {
  void * jresult ;
  Project *arg1 = (Project *) 0 ;
  char *arg2 = (char *) 0 ;
  ListObjectsOptions *arg3 = (ListObjectsOptions *) 0 ;
  ObjectIterator *result = 0 ;
  
  arg1 = (Project *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (ListObjectsOptions *)jarg3; 
  result = (ObjectIterator *)list_objects(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT _Bool SWIGSTDCALL CSharp_uplinkfSWIG_object_iterator_next___(void * jarg1) {
  _Bool jresult ;
  ObjectIterator *arg1 = (ObjectIterator *) 0 ;
  _Bool result;
  
  arg1 = (ObjectIterator *)jarg1; 
  result = object_iterator_next(arg1);
  jresult = (_Bool)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_object_iterator_err___(void * jarg1) {
  void * jresult ;
  ObjectIterator *arg1 = (ObjectIterator *) 0 ;
  Error *result = 0 ;
  
  arg1 = (ObjectIterator *)jarg1; 
  result = (Error *)object_iterator_err(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_object_iterator_item___(void * jarg1) {
  void * jresult ;
  ObjectIterator *arg1 = (ObjectIterator *) 0 ;
  Object *result = 0 ;
  
  arg1 = (ObjectIterator *)jarg1; 
  result = (Object *)object_iterator_item(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_object_iterator___(void * jarg1) {
  ObjectIterator *arg1 = (ObjectIterator *) 0 ;
  
  arg1 = (ObjectIterator *)jarg1; 
  free_object_iterator(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_open_project___(void * jarg1) {
  void * jresult ;
  Access *arg1 = (Access *) 0 ;
  ProjectResult result;
  
  arg1 = (Access *)jarg1; 
  result = open_project(arg1);
  {
    ProjectResult * resultptr = (ProjectResult *) malloc(sizeof(ProjectResult));
    memmove(resultptr, &result, sizeof(ProjectResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_close_project___(void * jarg1) {
  void * jresult ;
  Project *arg1 = (Project *) 0 ;
  Error *result = 0 ;
  
  arg1 = (Project *)jarg1; 
  result = (Error *)close_project(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_project_result___(void * jarg1) {
  ProjectResult arg1 ;
  ProjectResult *argp1 ;
  
  argp1 = (ProjectResult *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null ProjectResult", 0);
    return ;
  }
  arg1 = *argp1; 
  free_project_result(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_prepare_shareprefixes___(unsigned long jarg1) {
  size_t arg1 ;
  
  arg1 = (size_t)jarg1; 
  prepare_shareprefixes(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_append_shareprefix___(char * jarg1, char * jarg2) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (char *)jarg1; 
  arg2 = (char *)jarg2; 
  append_shareprefix(arg1,arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_access_share2___(void * jarg1, void * jarg2) {
  void * jresult ;
  Access *arg1 = (Access *) 0 ;
  Permission arg2 ;
  Permission *argp2 ;
  AccessResult result;
  
  arg1 = (Access *)jarg1; 
  argp2 = (Permission *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null Permission", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = access_share2(arg1,arg2);
  {
    AccessResult * resultptr = (AccessResult *) malloc(sizeof(AccessResult));
    memmove(resultptr, &result, sizeof(AccessResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_upload_object___(void * jarg1, char * jarg2, char * jarg3, void * jarg4) {
  void * jresult ;
  Project *arg1 = (Project *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  UploadOptions *arg4 = (UploadOptions *) 0 ;
  UploadResult result;
  
  arg1 = (Project *)jarg1; 
  arg2 = (char *)jarg2; 
  arg3 = (char *)jarg3; 
  arg4 = (UploadOptions *)jarg4; 
  result = upload_object(arg1,arg2,arg3,arg4);
  {
    UploadResult * resultptr = (UploadResult *) malloc(sizeof(UploadResult));
    memmove(resultptr, &result, sizeof(UploadResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_upload_write___(void * jarg1, void * jarg2, unsigned long jarg3) {
  void * jresult ;
  Upload *arg1 = (Upload *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  WriteResult result;
  
  arg1 = (Upload *)jarg1; 
  arg2 = (void *)jarg2; 
  arg3 = (size_t)jarg3; 
  result = upload_write(arg1,arg2,arg3);
  {
    WriteResult * resultptr = (WriteResult *) malloc(sizeof(WriteResult));
    memmove(resultptr, &result, sizeof(WriteResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_upload_commit___(void * jarg1) {
  void * jresult ;
  Upload *arg1 = (Upload *) 0 ;
  Error *result = 0 ;
  
  arg1 = (Upload *)jarg1; 
  result = (Error *)upload_commit(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_upload_abort___(void * jarg1) {
  void * jresult ;
  Upload *arg1 = (Upload *) 0 ;
  Error *result = 0 ;
  
  arg1 = (Upload *)jarg1; 
  result = (Error *)upload_abort(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_upload_info___(void * jarg1) {
  void * jresult ;
  Upload *arg1 = (Upload *) 0 ;
  ObjectResult result;
  
  arg1 = (Upload *)jarg1; 
  result = upload_info(arg1);
  {
    ObjectResult * resultptr = (ObjectResult *) malloc(sizeof(ObjectResult));
    memmove(resultptr, &result, sizeof(ObjectResult));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_upload_set_custom_metadata___(void * jarg1, void * jarg2) {
  void * jresult ;
  Upload *arg1 = (Upload *) 0 ;
  CustomMetadata arg2 ;
  CustomMetadata *argp2 ;
  Error *result = 0 ;
  
  arg1 = (Upload *)jarg1; 
  argp2 = (CustomMetadata *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null CustomMetadata", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (Error *)upload_set_custom_metadata(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_write_result___(void * jarg1) {
  WriteResult arg1 ;
  WriteResult *argp1 ;
  
  argp1 = (WriteResult *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null WriteResult", 0);
    return ;
  }
  arg1 = *argp1; 
  free_write_result(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_free_upload_result___(void * jarg1) {
  UploadResult arg1 ;
  UploadResult *argp1 ;
  
  argp1 = (UploadResult *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null UploadResult", 0);
    return ;
  }
  arg1 = *argp1; 
  free_upload_result(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Handle__handle_set___(void * jarg1, unsigned long jarg2) {
  struct Handle *arg1 = (struct Handle *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct Handle *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->_handle = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_uplinkfSWIG_Handle__handle_get___(void * jarg1) {
  unsigned long jresult ;
  struct Handle *arg1 = (struct Handle *) 0 ;
  size_t result;
  
  arg1 = (struct Handle *)jarg1; 
  result =  ((arg1)->_handle);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_Handle___() {
  void * jresult ;
  struct Handle *result = 0 ;
  
  result = (struct Handle *)calloc(1, sizeof(struct Handle));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_Handle___(void * jarg1) {
  struct Handle *arg1 = (struct Handle *) 0 ;
  
  arg1 = (struct Handle *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Access__handle_set___(void * jarg1, unsigned long jarg2) {
  struct Access *arg1 = (struct Access *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct Access *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->_handle = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_uplinkfSWIG_Access__handle_get___(void * jarg1) {
  unsigned long jresult ;
  struct Access *arg1 = (struct Access *) 0 ;
  size_t result;
  
  arg1 = (struct Access *)jarg1; 
  result =  ((arg1)->_handle);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_Access___() {
  void * jresult ;
  struct Access *result = 0 ;
  
  result = (struct Access *)calloc(1, sizeof(struct Access));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_Access___(void * jarg1) {
  struct Access *arg1 = (struct Access *) 0 ;
  
  arg1 = (struct Access *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Project__handle_set___(void * jarg1, unsigned long jarg2) {
  struct Project *arg1 = (struct Project *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct Project *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->_handle = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_uplinkfSWIG_Project__handle_get___(void * jarg1) {
  unsigned long jresult ;
  struct Project *arg1 = (struct Project *) 0 ;
  size_t result;
  
  arg1 = (struct Project *)jarg1; 
  result =  ((arg1)->_handle);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_Project___() {
  void * jresult ;
  struct Project *result = 0 ;
  
  result = (struct Project *)calloc(1, sizeof(struct Project));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_Project___(void * jarg1) {
  struct Project *arg1 = (struct Project *) 0 ;
  
  arg1 = (struct Project *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Download__handle_set___(void * jarg1, unsigned long jarg2) {
  struct Download *arg1 = (struct Download *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct Download *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->_handle = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_uplinkfSWIG_Download__handle_get___(void * jarg1) {
  unsigned long jresult ;
  struct Download *arg1 = (struct Download *) 0 ;
  size_t result;
  
  arg1 = (struct Download *)jarg1; 
  result =  ((arg1)->_handle);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_Download___() {
  void * jresult ;
  struct Download *result = 0 ;
  
  result = (struct Download *)calloc(1, sizeof(struct Download));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_Download___(void * jarg1) {
  struct Download *arg1 = (struct Download *) 0 ;
  
  arg1 = (struct Download *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Upload__handle_set___(void * jarg1, unsigned long jarg2) {
  struct Upload *arg1 = (struct Upload *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct Upload *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->_handle = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_uplinkfSWIG_Upload__handle_get___(void * jarg1) {
  unsigned long jresult ;
  struct Upload *arg1 = (struct Upload *) 0 ;
  size_t result;
  
  arg1 = (struct Upload *)jarg1; 
  result =  ((arg1)->_handle);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_Upload___() {
  void * jresult ;
  struct Upload *result = 0 ;
  
  result = (struct Upload *)calloc(1, sizeof(struct Upload));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_Upload___(void * jarg1) {
  struct Upload *arg1 = (struct Upload *) 0 ;
  
  arg1 = (struct Upload *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Config_user_agent_set___(void * jarg1, char * jarg2) {
  struct Config *arg1 = (struct Config *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct Config *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->user_agent);
    if (arg2) {
      arg1->user_agent = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->user_agent, (const char *)arg2);
    } else {
      arg1->user_agent = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_Config_user_agent_get___(void * jarg1) {
  char * jresult ;
  struct Config *arg1 = (struct Config *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct Config *)jarg1; 
  result = (char *) ((arg1)->user_agent);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Config_dial_timeout_milliseconds_set___(void * jarg1, int32_t jarg2) {
  struct Config *arg1 = (struct Config *) 0 ;
  int32_t arg2 ;
  
  arg1 = (struct Config *)jarg1; 
  arg2 = (int32_t)jarg2; 
  if (arg1) (arg1)->dial_timeout_milliseconds = arg2;
}


SWIGEXPORT int32_t SWIGSTDCALL CSharp_uplinkfSWIG_Config_dial_timeout_milliseconds_get___(void * jarg1) {
  int32_t jresult ;
  struct Config *arg1 = (struct Config *) 0 ;
  int32_t result;
  
  arg1 = (struct Config *)jarg1; 
  result =  ((arg1)->dial_timeout_milliseconds);
  jresult = (int32_t)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Config_temp_directory_set___(void * jarg1, char * jarg2) {
  struct Config *arg1 = (struct Config *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct Config *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->temp_directory);
    if (arg2) {
      arg1->temp_directory = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->temp_directory, (const char *)arg2);
    } else {
      arg1->temp_directory = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_Config_temp_directory_get___(void * jarg1) {
  char * jresult ;
  struct Config *arg1 = (struct Config *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct Config *)jarg1; 
  result = (char *) ((arg1)->temp_directory);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_Config___() {
  void * jresult ;
  struct Config *result = 0 ;
  
  result = (struct Config *)calloc(1, sizeof(struct Config));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_Config___(void * jarg1) {
  struct Config *arg1 = (struct Config *) 0 ;
  
  arg1 = (struct Config *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Bucket_name_set___(void * jarg1, char * jarg2) {
  struct Bucket *arg1 = (struct Bucket *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct Bucket *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->name);
    if (arg2) {
      arg1->name = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->name, (const char *)arg2);
    } else {
      arg1->name = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_Bucket_name_get___(void * jarg1) {
  char * jresult ;
  struct Bucket *arg1 = (struct Bucket *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct Bucket *)jarg1; 
  result = (char *) ((arg1)->name);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Bucket_created_set___(void * jarg1, int64_t jarg2) {
  struct Bucket *arg1 = (struct Bucket *) 0 ;
  int64_t arg2 ;
  
  arg1 = (struct Bucket *)jarg1; 
  arg2 = (int64_t)jarg2; 
  if (arg1) (arg1)->created = arg2;
}


SWIGEXPORT int64_t SWIGSTDCALL CSharp_uplinkfSWIG_Bucket_created_get___(void * jarg1) {
  int64_t jresult ;
  struct Bucket *arg1 = (struct Bucket *) 0 ;
  int64_t result;
  
  arg1 = (struct Bucket *)jarg1; 
  result =  ((arg1)->created);
  jresult = (int64_t)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_Bucket___() {
  void * jresult ;
  struct Bucket *result = 0 ;
  
  result = (struct Bucket *)calloc(1, sizeof(struct Bucket));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_Bucket___(void * jarg1) {
  struct Bucket *arg1 = (struct Bucket *) 0 ;
  
  arg1 = (struct Bucket *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_SystemMetadata_created_set___(void * jarg1, int64_t jarg2) {
  struct SystemMetadata *arg1 = (struct SystemMetadata *) 0 ;
  int64_t arg2 ;
  
  arg1 = (struct SystemMetadata *)jarg1; 
  arg2 = (int64_t)jarg2; 
  if (arg1) (arg1)->created = arg2;
}


SWIGEXPORT int64_t SWIGSTDCALL CSharp_uplinkfSWIG_SystemMetadata_created_get___(void * jarg1) {
  int64_t jresult ;
  struct SystemMetadata *arg1 = (struct SystemMetadata *) 0 ;
  int64_t result;
  
  arg1 = (struct SystemMetadata *)jarg1; 
  result =  ((arg1)->created);
  jresult = (int64_t)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_SystemMetadata_expires_set___(void * jarg1, int64_t jarg2) {
  struct SystemMetadata *arg1 = (struct SystemMetadata *) 0 ;
  int64_t arg2 ;
  
  arg1 = (struct SystemMetadata *)jarg1; 
  arg2 = (int64_t)jarg2; 
  if (arg1) (arg1)->expires = arg2;
}


SWIGEXPORT int64_t SWIGSTDCALL CSharp_uplinkfSWIG_SystemMetadata_expires_get___(void * jarg1) {
  int64_t jresult ;
  struct SystemMetadata *arg1 = (struct SystemMetadata *) 0 ;
  int64_t result;
  
  arg1 = (struct SystemMetadata *)jarg1; 
  result =  ((arg1)->expires);
  jresult = (int64_t)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_SystemMetadata_content_length_set___(void * jarg1, int64_t jarg2) {
  struct SystemMetadata *arg1 = (struct SystemMetadata *) 0 ;
  int64_t arg2 ;
  
  arg1 = (struct SystemMetadata *)jarg1; 
  arg2 = (int64_t)jarg2; 
  if (arg1) (arg1)->content_length = arg2;
}


SWIGEXPORT int64_t SWIGSTDCALL CSharp_uplinkfSWIG_SystemMetadata_content_length_get___(void * jarg1) {
  int64_t jresult ;
  struct SystemMetadata *arg1 = (struct SystemMetadata *) 0 ;
  int64_t result;
  
  arg1 = (struct SystemMetadata *)jarg1; 
  result =  ((arg1)->content_length);
  jresult = (int64_t)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_SystemMetadata___() {
  void * jresult ;
  struct SystemMetadata *result = 0 ;
  
  result = (struct SystemMetadata *)calloc(1, sizeof(struct SystemMetadata));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_SystemMetadata___(void * jarg1) {
  struct SystemMetadata *arg1 = (struct SystemMetadata *) 0 ;
  
  arg1 = (struct SystemMetadata *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_CustomMetadataEntry_key_set___(void * jarg1, char * jarg2) {
  struct CustomMetadataEntry *arg1 = (struct CustomMetadataEntry *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct CustomMetadataEntry *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->key);
    if (arg2) {
      arg1->key = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->key, (const char *)arg2);
    } else {
      arg1->key = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_CustomMetadataEntry_key_get___(void * jarg1) {
  char * jresult ;
  struct CustomMetadataEntry *arg1 = (struct CustomMetadataEntry *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct CustomMetadataEntry *)jarg1; 
  result = (char *) ((arg1)->key);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_CustomMetadataEntry_key_length_set___(void * jarg1, unsigned long jarg2) {
  struct CustomMetadataEntry *arg1 = (struct CustomMetadataEntry *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct CustomMetadataEntry *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->key_length = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_uplinkfSWIG_CustomMetadataEntry_key_length_get___(void * jarg1) {
  unsigned long jresult ;
  struct CustomMetadataEntry *arg1 = (struct CustomMetadataEntry *) 0 ;
  size_t result;
  
  arg1 = (struct CustomMetadataEntry *)jarg1; 
  result =  ((arg1)->key_length);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_CustomMetadataEntry_value_set___(void * jarg1, char * jarg2) {
  struct CustomMetadataEntry *arg1 = (struct CustomMetadataEntry *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct CustomMetadataEntry *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->value);
    if (arg2) {
      arg1->value = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->value, (const char *)arg2);
    } else {
      arg1->value = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_CustomMetadataEntry_value_get___(void * jarg1) {
  char * jresult ;
  struct CustomMetadataEntry *arg1 = (struct CustomMetadataEntry *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct CustomMetadataEntry *)jarg1; 
  result = (char *) ((arg1)->value);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_CustomMetadataEntry_value_length_set___(void * jarg1, unsigned long jarg2) {
  struct CustomMetadataEntry *arg1 = (struct CustomMetadataEntry *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct CustomMetadataEntry *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->value_length = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_uplinkfSWIG_CustomMetadataEntry_value_length_get___(void * jarg1) {
  unsigned long jresult ;
  struct CustomMetadataEntry *arg1 = (struct CustomMetadataEntry *) 0 ;
  size_t result;
  
  arg1 = (struct CustomMetadataEntry *)jarg1; 
  result =  ((arg1)->value_length);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_CustomMetadataEntry___() {
  void * jresult ;
  struct CustomMetadataEntry *result = 0 ;
  
  result = (struct CustomMetadataEntry *)calloc(1, sizeof(struct CustomMetadataEntry));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_CustomMetadataEntry___(void * jarg1) {
  struct CustomMetadataEntry *arg1 = (struct CustomMetadataEntry *) 0 ;
  
  arg1 = (struct CustomMetadataEntry *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_CustomMetadata_entries_set___(void * jarg1, void * jarg2) {
  struct CustomMetadata *arg1 = (struct CustomMetadata *) 0 ;
  CustomMetadataEntry *arg2 = (CustomMetadataEntry *) 0 ;
  
  arg1 = (struct CustomMetadata *)jarg1; 
  arg2 = (CustomMetadataEntry *)jarg2; 
  if (arg1) (arg1)->entries = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_CustomMetadata_entries_get___(void * jarg1) {
  void * jresult ;
  struct CustomMetadata *arg1 = (struct CustomMetadata *) 0 ;
  CustomMetadataEntry *result = 0 ;
  
  arg1 = (struct CustomMetadata *)jarg1; 
  result = (CustomMetadataEntry *) ((arg1)->entries);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_CustomMetadata_count_set___(void * jarg1, unsigned long jarg2) {
  struct CustomMetadata *arg1 = (struct CustomMetadata *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct CustomMetadata *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->count = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_uplinkfSWIG_CustomMetadata_count_get___(void * jarg1) {
  unsigned long jresult ;
  struct CustomMetadata *arg1 = (struct CustomMetadata *) 0 ;
  size_t result;
  
  arg1 = (struct CustomMetadata *)jarg1; 
  result =  ((arg1)->count);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_CustomMetadata___() {
  void * jresult ;
  struct CustomMetadata *result = 0 ;
  
  result = (struct CustomMetadata *)calloc(1, sizeof(struct CustomMetadata));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_CustomMetadata___(void * jarg1) {
  struct CustomMetadata *arg1 = (struct CustomMetadata *) 0 ;
  
  arg1 = (struct CustomMetadata *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Object_key_set___(void * jarg1, char * jarg2) {
  struct Object *arg1 = (struct Object *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct Object *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->key);
    if (arg2) {
      arg1->key = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->key, (const char *)arg2);
    } else {
      arg1->key = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_Object_key_get___(void * jarg1) {
  char * jresult ;
  struct Object *arg1 = (struct Object *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct Object *)jarg1; 
  result = (char *) ((arg1)->key);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Object_is_prefix_set___(void * jarg1, unsigned int jarg2) {
  struct Object *arg1 = (struct Object *) 0 ;
  bool arg2 ;
  
  arg1 = (struct Object *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->is_prefix = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_uplinkfSWIG_Object_is_prefix_get___(void * jarg1) {
  unsigned int jresult ;
  struct Object *arg1 = (struct Object *) 0 ;
  bool result;
  
  arg1 = (struct Object *)jarg1; 
  result = (bool) ((arg1)->is_prefix);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Object_system_set___(void * jarg1, void * jarg2) {
  struct Object *arg1 = (struct Object *) 0 ;
  SystemMetadata *arg2 = (SystemMetadata *) 0 ;
  
  arg1 = (struct Object *)jarg1; 
  arg2 = (SystemMetadata *)jarg2; 
  if (arg1) (arg1)->system = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_Object_system_get___(void * jarg1) {
  void * jresult ;
  struct Object *arg1 = (struct Object *) 0 ;
  SystemMetadata *result = 0 ;
  
  arg1 = (struct Object *)jarg1; 
  result = (SystemMetadata *)& ((arg1)->system);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Object_custom_set___(void * jarg1, void * jarg2) {
  struct Object *arg1 = (struct Object *) 0 ;
  CustomMetadata *arg2 = (CustomMetadata *) 0 ;
  
  arg1 = (struct Object *)jarg1; 
  arg2 = (CustomMetadata *)jarg2; 
  if (arg1) (arg1)->custom = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_Object_custom_get___(void * jarg1) {
  void * jresult ;
  struct Object *arg1 = (struct Object *) 0 ;
  CustomMetadata *result = 0 ;
  
  arg1 = (struct Object *)jarg1; 
  result = (CustomMetadata *)& ((arg1)->custom);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_Object___() {
  void * jresult ;
  struct Object *result = 0 ;
  
  result = (struct Object *)calloc(1, sizeof(struct Object));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_Object___(void * jarg1) {
  struct Object *arg1 = (struct Object *) 0 ;
  
  arg1 = (struct Object *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_UploadOptions_expires_set___(void * jarg1, int64_t jarg2) {
  struct UploadOptions *arg1 = (struct UploadOptions *) 0 ;
  int64_t arg2 ;
  
  arg1 = (struct UploadOptions *)jarg1; 
  arg2 = (int64_t)jarg2; 
  if (arg1) (arg1)->expires = arg2;
}


SWIGEXPORT int64_t SWIGSTDCALL CSharp_uplinkfSWIG_UploadOptions_expires_get___(void * jarg1) {
  int64_t jresult ;
  struct UploadOptions *arg1 = (struct UploadOptions *) 0 ;
  int64_t result;
  
  arg1 = (struct UploadOptions *)jarg1; 
  result =  ((arg1)->expires);
  jresult = (int64_t)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_UploadOptions___() {
  void * jresult ;
  struct UploadOptions *result = 0 ;
  
  result = (struct UploadOptions *)calloc(1, sizeof(struct UploadOptions));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_UploadOptions___(void * jarg1) {
  struct UploadOptions *arg1 = (struct UploadOptions *) 0 ;
  
  arg1 = (struct UploadOptions *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_DownloadOptions_offset_set___(void * jarg1, int64_t jarg2) {
  struct DownloadOptions *arg1 = (struct DownloadOptions *) 0 ;
  int64_t arg2 ;
  
  arg1 = (struct DownloadOptions *)jarg1; 
  arg2 = (int64_t)jarg2; 
  if (arg1) (arg1)->offset = arg2;
}


SWIGEXPORT int64_t SWIGSTDCALL CSharp_uplinkfSWIG_DownloadOptions_offset_get___(void * jarg1) {
  int64_t jresult ;
  struct DownloadOptions *arg1 = (struct DownloadOptions *) 0 ;
  int64_t result;
  
  arg1 = (struct DownloadOptions *)jarg1; 
  result =  ((arg1)->offset);
  jresult = (int64_t)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_DownloadOptions_length_set___(void * jarg1, int64_t jarg2) {
  struct DownloadOptions *arg1 = (struct DownloadOptions *) 0 ;
  int64_t arg2 ;
  
  arg1 = (struct DownloadOptions *)jarg1; 
  arg2 = (int64_t)jarg2; 
  if (arg1) (arg1)->length = arg2;
}


SWIGEXPORT int64_t SWIGSTDCALL CSharp_uplinkfSWIG_DownloadOptions_length_get___(void * jarg1) {
  int64_t jresult ;
  struct DownloadOptions *arg1 = (struct DownloadOptions *) 0 ;
  int64_t result;
  
  arg1 = (struct DownloadOptions *)jarg1; 
  result =  ((arg1)->length);
  jresult = (int64_t)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_DownloadOptions___() {
  void * jresult ;
  struct DownloadOptions *result = 0 ;
  
  result = (struct DownloadOptions *)calloc(1, sizeof(struct DownloadOptions));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_DownloadOptions___(void * jarg1) {
  struct DownloadOptions *arg1 = (struct DownloadOptions *) 0 ;
  
  arg1 = (struct DownloadOptions *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_ListObjectsOptions_prefix_set___(void * jarg1, char * jarg2) {
  struct ListObjectsOptions *arg1 = (struct ListObjectsOptions *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct ListObjectsOptions *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->prefix);
    if (arg2) {
      arg1->prefix = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->prefix, (const char *)arg2);
    } else {
      arg1->prefix = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_ListObjectsOptions_prefix_get___(void * jarg1) {
  char * jresult ;
  struct ListObjectsOptions *arg1 = (struct ListObjectsOptions *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct ListObjectsOptions *)jarg1; 
  result = (char *) ((arg1)->prefix);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_ListObjectsOptions_cursor_set___(void * jarg1, char * jarg2) {
  struct ListObjectsOptions *arg1 = (struct ListObjectsOptions *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct ListObjectsOptions *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->cursor);
    if (arg2) {
      arg1->cursor = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->cursor, (const char *)arg2);
    } else {
      arg1->cursor = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_ListObjectsOptions_cursor_get___(void * jarg1) {
  char * jresult ;
  struct ListObjectsOptions *arg1 = (struct ListObjectsOptions *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct ListObjectsOptions *)jarg1; 
  result = (char *) ((arg1)->cursor);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_ListObjectsOptions_recursive_set___(void * jarg1, unsigned int jarg2) {
  struct ListObjectsOptions *arg1 = (struct ListObjectsOptions *) 0 ;
  bool arg2 ;
  
  arg1 = (struct ListObjectsOptions *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->recursive = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_uplinkfSWIG_ListObjectsOptions_recursive_get___(void * jarg1) {
  unsigned int jresult ;
  struct ListObjectsOptions *arg1 = (struct ListObjectsOptions *) 0 ;
  bool result;
  
  arg1 = (struct ListObjectsOptions *)jarg1; 
  result = (bool) ((arg1)->recursive);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_ListObjectsOptions_system_set___(void * jarg1, unsigned int jarg2) {
  struct ListObjectsOptions *arg1 = (struct ListObjectsOptions *) 0 ;
  bool arg2 ;
  
  arg1 = (struct ListObjectsOptions *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->system = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_uplinkfSWIG_ListObjectsOptions_system_get___(void * jarg1) {
  unsigned int jresult ;
  struct ListObjectsOptions *arg1 = (struct ListObjectsOptions *) 0 ;
  bool result;
  
  arg1 = (struct ListObjectsOptions *)jarg1; 
  result = (bool) ((arg1)->system);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_ListObjectsOptions_custom_set___(void * jarg1, unsigned int jarg2) {
  struct ListObjectsOptions *arg1 = (struct ListObjectsOptions *) 0 ;
  bool arg2 ;
  
  arg1 = (struct ListObjectsOptions *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->custom = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_uplinkfSWIG_ListObjectsOptions_custom_get___(void * jarg1) {
  unsigned int jresult ;
  struct ListObjectsOptions *arg1 = (struct ListObjectsOptions *) 0 ;
  bool result;
  
  arg1 = (struct ListObjectsOptions *)jarg1; 
  result = (bool) ((arg1)->custom);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_ListObjectsOptions___() {
  void * jresult ;
  struct ListObjectsOptions *result = 0 ;
  
  result = (struct ListObjectsOptions *)calloc(1, sizeof(struct ListObjectsOptions));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_ListObjectsOptions___(void * jarg1) {
  struct ListObjectsOptions *arg1 = (struct ListObjectsOptions *) 0 ;
  
  arg1 = (struct ListObjectsOptions *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_ListBucketsOptions_cursor_set___(void * jarg1, char * jarg2) {
  struct ListBucketsOptions *arg1 = (struct ListBucketsOptions *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct ListBucketsOptions *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->cursor);
    if (arg2) {
      arg1->cursor = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->cursor, (const char *)arg2);
    } else {
      arg1->cursor = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_ListBucketsOptions_cursor_get___(void * jarg1) {
  char * jresult ;
  struct ListBucketsOptions *arg1 = (struct ListBucketsOptions *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct ListBucketsOptions *)jarg1; 
  result = (char *) ((arg1)->cursor);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_ListBucketsOptions___() {
  void * jresult ;
  struct ListBucketsOptions *result = 0 ;
  
  result = (struct ListBucketsOptions *)calloc(1, sizeof(struct ListBucketsOptions));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_ListBucketsOptions___(void * jarg1) {
  struct ListBucketsOptions *arg1 = (struct ListBucketsOptions *) 0 ;
  
  arg1 = (struct ListBucketsOptions *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_ObjectIterator__handle_set___(void * jarg1, unsigned long jarg2) {
  struct ObjectIterator *arg1 = (struct ObjectIterator *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct ObjectIterator *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->_handle = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_uplinkfSWIG_ObjectIterator__handle_get___(void * jarg1) {
  unsigned long jresult ;
  struct ObjectIterator *arg1 = (struct ObjectIterator *) 0 ;
  size_t result;
  
  arg1 = (struct ObjectIterator *)jarg1; 
  result =  ((arg1)->_handle);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_ObjectIterator___() {
  void * jresult ;
  struct ObjectIterator *result = 0 ;
  
  result = (struct ObjectIterator *)calloc(1, sizeof(struct ObjectIterator));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_ObjectIterator___(void * jarg1) {
  struct ObjectIterator *arg1 = (struct ObjectIterator *) 0 ;
  
  arg1 = (struct ObjectIterator *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_BucketIterator__handle_set___(void * jarg1, unsigned long jarg2) {
  struct BucketIterator *arg1 = (struct BucketIterator *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct BucketIterator *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->_handle = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_uplinkfSWIG_BucketIterator__handle_get___(void * jarg1) {
  unsigned long jresult ;
  struct BucketIterator *arg1 = (struct BucketIterator *) 0 ;
  size_t result;
  
  arg1 = (struct BucketIterator *)jarg1; 
  result =  ((arg1)->_handle);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_BucketIterator___() {
  void * jresult ;
  struct BucketIterator *result = 0 ;
  
  result = (struct BucketIterator *)calloc(1, sizeof(struct BucketIterator));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_BucketIterator___(void * jarg1) {
  struct BucketIterator *arg1 = (struct BucketIterator *) 0 ;
  
  arg1 = (struct BucketIterator *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Permission_allow_download_set___(void * jarg1, unsigned int jarg2) {
  struct Permission *arg1 = (struct Permission *) 0 ;
  bool arg2 ;
  
  arg1 = (struct Permission *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->allow_download = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_uplinkfSWIG_Permission_allow_download_get___(void * jarg1) {
  unsigned int jresult ;
  struct Permission *arg1 = (struct Permission *) 0 ;
  bool result;
  
  arg1 = (struct Permission *)jarg1; 
  result = (bool) ((arg1)->allow_download);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Permission_allow_upload_set___(void * jarg1, unsigned int jarg2) {
  struct Permission *arg1 = (struct Permission *) 0 ;
  bool arg2 ;
  
  arg1 = (struct Permission *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->allow_upload = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_uplinkfSWIG_Permission_allow_upload_get___(void * jarg1) {
  unsigned int jresult ;
  struct Permission *arg1 = (struct Permission *) 0 ;
  bool result;
  
  arg1 = (struct Permission *)jarg1; 
  result = (bool) ((arg1)->allow_upload);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Permission_allow_list_set___(void * jarg1, unsigned int jarg2) {
  struct Permission *arg1 = (struct Permission *) 0 ;
  bool arg2 ;
  
  arg1 = (struct Permission *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->allow_list = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_uplinkfSWIG_Permission_allow_list_get___(void * jarg1) {
  unsigned int jresult ;
  struct Permission *arg1 = (struct Permission *) 0 ;
  bool result;
  
  arg1 = (struct Permission *)jarg1; 
  result = (bool) ((arg1)->allow_list);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Permission_allow_delete_set___(void * jarg1, unsigned int jarg2) {
  struct Permission *arg1 = (struct Permission *) 0 ;
  bool arg2 ;
  
  arg1 = (struct Permission *)jarg1; 
  arg2 = jarg2 ? true : false; 
  if (arg1) (arg1)->allow_delete = arg2;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_uplinkfSWIG_Permission_allow_delete_get___(void * jarg1) {
  unsigned int jresult ;
  struct Permission *arg1 = (struct Permission *) 0 ;
  bool result;
  
  arg1 = (struct Permission *)jarg1; 
  result = (bool) ((arg1)->allow_delete);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Permission_not_before_set___(void * jarg1, int64_t jarg2) {
  struct Permission *arg1 = (struct Permission *) 0 ;
  int64_t arg2 ;
  
  arg1 = (struct Permission *)jarg1; 
  arg2 = (int64_t)jarg2; 
  if (arg1) (arg1)->not_before = arg2;
}


SWIGEXPORT int64_t SWIGSTDCALL CSharp_uplinkfSWIG_Permission_not_before_get___(void * jarg1) {
  int64_t jresult ;
  struct Permission *arg1 = (struct Permission *) 0 ;
  int64_t result;
  
  arg1 = (struct Permission *)jarg1; 
  result =  ((arg1)->not_before);
  jresult = (int64_t)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Permission_not_after_set___(void * jarg1, int64_t jarg2) {
  struct Permission *arg1 = (struct Permission *) 0 ;
  int64_t arg2 ;
  
  arg1 = (struct Permission *)jarg1; 
  arg2 = (int64_t)jarg2; 
  if (arg1) (arg1)->not_after = arg2;
}


SWIGEXPORT int64_t SWIGSTDCALL CSharp_uplinkfSWIG_Permission_not_after_get___(void * jarg1) {
  int64_t jresult ;
  struct Permission *arg1 = (struct Permission *) 0 ;
  int64_t result;
  
  arg1 = (struct Permission *)jarg1; 
  result =  ((arg1)->not_after);
  jresult = (int64_t)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_Permission___() {
  void * jresult ;
  struct Permission *result = 0 ;
  
  result = (struct Permission *)calloc(1, sizeof(struct Permission));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_Permission___(void * jarg1) {
  struct Permission *arg1 = (struct Permission *) 0 ;
  
  arg1 = (struct Permission *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_SharePrefix_bucket_set___(void * jarg1, char * jarg2) {
  struct SharePrefix *arg1 = (struct SharePrefix *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct SharePrefix *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->bucket);
    if (arg2) {
      arg1->bucket = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->bucket, (const char *)arg2);
    } else {
      arg1->bucket = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_SharePrefix_bucket_get___(void * jarg1) {
  char * jresult ;
  struct SharePrefix *arg1 = (struct SharePrefix *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct SharePrefix *)jarg1; 
  result = (char *) ((arg1)->bucket);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_SharePrefix_prefix_set___(void * jarg1, char * jarg2) {
  struct SharePrefix *arg1 = (struct SharePrefix *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct SharePrefix *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->prefix);
    if (arg2) {
      arg1->prefix = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->prefix, (const char *)arg2);
    } else {
      arg1->prefix = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_SharePrefix_prefix_get___(void * jarg1) {
  char * jresult ;
  struct SharePrefix *arg1 = (struct SharePrefix *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct SharePrefix *)jarg1; 
  result = (char *) ((arg1)->prefix);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_SharePrefix___() {
  void * jresult ;
  struct SharePrefix *result = 0 ;
  
  result = (struct SharePrefix *)calloc(1, sizeof(struct SharePrefix));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_SharePrefix___(void * jarg1) {
  struct SharePrefix *arg1 = (struct SharePrefix *) 0 ;
  
  arg1 = (struct SharePrefix *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Error_code_set___(void * jarg1, int32_t jarg2) {
  struct Error *arg1 = (struct Error *) 0 ;
  int32_t arg2 ;
  
  arg1 = (struct Error *)jarg1; 
  arg2 = (int32_t)jarg2; 
  if (arg1) (arg1)->code = arg2;
}


SWIGEXPORT int32_t SWIGSTDCALL CSharp_uplinkfSWIG_Error_code_get___(void * jarg1) {
  int32_t jresult ;
  struct Error *arg1 = (struct Error *) 0 ;
  int32_t result;
  
  arg1 = (struct Error *)jarg1; 
  result =  ((arg1)->code);
  jresult = (int32_t)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_Error_message_set___(void * jarg1, char * jarg2) {
  struct Error *arg1 = (struct Error *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct Error *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->message);
    if (arg2) {
      arg1->message = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->message, (const char *)arg2);
    } else {
      arg1->message = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_Error_message_get___(void * jarg1) {
  char * jresult ;
  struct Error *arg1 = (struct Error *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct Error *)jarg1; 
  result = (char *) ((arg1)->message);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_Error___() {
  void * jresult ;
  struct Error *result = 0 ;
  
  result = (struct Error *)calloc(1, sizeof(struct Error));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_Error___(void * jarg1) {
  struct Error *arg1 = (struct Error *) 0 ;
  
  arg1 = (struct Error *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_uplinkfSWIG_ERROR_INTERNAL_get___() {
  int jresult ;
  int result;
  
  result = (int)(0x02);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_uplinkfSWIG_ERROR_CANCELED_get___() {
  int jresult ;
  int result;
  
  result = (int)(0x03);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_uplinkfSWIG_ERROR_INVALID_HANDLE_get___() {
  int jresult ;
  int result;
  
  result = (int)(0x04);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_uplinkfSWIG_ERROR_TOO_MANY_REQUESTS_get___() {
  int jresult ;
  int result;
  
  result = (int)(0x05);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_uplinkfSWIG_ERROR_BANDWIDTH_LIMIT_EXCEEDED_get___() {
  int jresult ;
  int result;
  
  result = (int)(0x06);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_uplinkfSWIG_ERROR_BUCKET_NAME_INVALID_get___() {
  int jresult ;
  int result;
  
  result = (int)(0x10);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_uplinkfSWIG_ERROR_BUCKET_ALREADY_EXISTS_get___() {
  int jresult ;
  int result;
  
  result = (int)(0x11);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_uplinkfSWIG_ERROR_BUCKET_NOT_EMPTY_get___() {
  int jresult ;
  int result;
  
  result = (int)(0x12);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_uplinkfSWIG_ERROR_BUCKET_NOT_FOUND_get___() {
  int jresult ;
  int result;
  
  result = (int)(0x13);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_uplinkfSWIG_ERROR_OBJECT_KEY_INVALID_get___() {
  int jresult ;
  int result;
  
  result = (int)(0x20);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_uplinkfSWIG_ERROR_OBJECT_NOT_FOUND_get___() {
  int jresult ;
  int result;
  
  result = (int)(0x21);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_uplinkfSWIG_ERROR_UPLOAD_DONE_get___() {
  int jresult ;
  int result;
  
  result = (int)(0x22);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_AccessResult_access_set___(void * jarg1, void * jarg2) {
  struct AccessResult *arg1 = (struct AccessResult *) 0 ;
  Access *arg2 = (Access *) 0 ;
  
  arg1 = (struct AccessResult *)jarg1; 
  arg2 = (Access *)jarg2; 
  if (arg1) (arg1)->access = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_AccessResult_access_get___(void * jarg1) {
  void * jresult ;
  struct AccessResult *arg1 = (struct AccessResult *) 0 ;
  Access *result = 0 ;
  
  arg1 = (struct AccessResult *)jarg1; 
  result = (Access *) ((arg1)->access);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_AccessResult_error_set___(void * jarg1, void * jarg2) {
  struct AccessResult *arg1 = (struct AccessResult *) 0 ;
  Error *arg2 = (Error *) 0 ;
  
  arg1 = (struct AccessResult *)jarg1; 
  arg2 = (Error *)jarg2; 
  if (arg1) (arg1)->error = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_AccessResult_error_get___(void * jarg1) {
  void * jresult ;
  struct AccessResult *arg1 = (struct AccessResult *) 0 ;
  Error *result = 0 ;
  
  arg1 = (struct AccessResult *)jarg1; 
  result = (Error *) ((arg1)->error);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_AccessResult___() {
  void * jresult ;
  struct AccessResult *result = 0 ;
  
  result = (struct AccessResult *)calloc(1, sizeof(struct AccessResult));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_AccessResult___(void * jarg1) {
  struct AccessResult *arg1 = (struct AccessResult *) 0 ;
  
  arg1 = (struct AccessResult *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_ProjectResult_project_set___(void * jarg1, void * jarg2) {
  struct ProjectResult *arg1 = (struct ProjectResult *) 0 ;
  Project *arg2 = (Project *) 0 ;
  
  arg1 = (struct ProjectResult *)jarg1; 
  arg2 = (Project *)jarg2; 
  if (arg1) (arg1)->project = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_ProjectResult_project_get___(void * jarg1) {
  void * jresult ;
  struct ProjectResult *arg1 = (struct ProjectResult *) 0 ;
  Project *result = 0 ;
  
  arg1 = (struct ProjectResult *)jarg1; 
  result = (Project *) ((arg1)->project);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_ProjectResult_error_set___(void * jarg1, void * jarg2) {
  struct ProjectResult *arg1 = (struct ProjectResult *) 0 ;
  Error *arg2 = (Error *) 0 ;
  
  arg1 = (struct ProjectResult *)jarg1; 
  arg2 = (Error *)jarg2; 
  if (arg1) (arg1)->error = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_ProjectResult_error_get___(void * jarg1) {
  void * jresult ;
  struct ProjectResult *arg1 = (struct ProjectResult *) 0 ;
  Error *result = 0 ;
  
  arg1 = (struct ProjectResult *)jarg1; 
  result = (Error *) ((arg1)->error);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_ProjectResult___() {
  void * jresult ;
  struct ProjectResult *result = 0 ;
  
  result = (struct ProjectResult *)calloc(1, sizeof(struct ProjectResult));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_ProjectResult___(void * jarg1) {
  struct ProjectResult *arg1 = (struct ProjectResult *) 0 ;
  
  arg1 = (struct ProjectResult *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_BucketResult_bucket_set___(void * jarg1, void * jarg2) {
  struct BucketResult *arg1 = (struct BucketResult *) 0 ;
  Bucket *arg2 = (Bucket *) 0 ;
  
  arg1 = (struct BucketResult *)jarg1; 
  arg2 = (Bucket *)jarg2; 
  if (arg1) (arg1)->bucket = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_BucketResult_bucket_get___(void * jarg1) {
  void * jresult ;
  struct BucketResult *arg1 = (struct BucketResult *) 0 ;
  Bucket *result = 0 ;
  
  arg1 = (struct BucketResult *)jarg1; 
  result = (Bucket *) ((arg1)->bucket);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_BucketResult_error_set___(void * jarg1, void * jarg2) {
  struct BucketResult *arg1 = (struct BucketResult *) 0 ;
  Error *arg2 = (Error *) 0 ;
  
  arg1 = (struct BucketResult *)jarg1; 
  arg2 = (Error *)jarg2; 
  if (arg1) (arg1)->error = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_BucketResult_error_get___(void * jarg1) {
  void * jresult ;
  struct BucketResult *arg1 = (struct BucketResult *) 0 ;
  Error *result = 0 ;
  
  arg1 = (struct BucketResult *)jarg1; 
  result = (Error *) ((arg1)->error);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_BucketResult___() {
  void * jresult ;
  struct BucketResult *result = 0 ;
  
  result = (struct BucketResult *)calloc(1, sizeof(struct BucketResult));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_BucketResult___(void * jarg1) {
  struct BucketResult *arg1 = (struct BucketResult *) 0 ;
  
  arg1 = (struct BucketResult *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_ObjectResult_object__set___(void * jarg1, void * jarg2) {
  struct ObjectResult *arg1 = (struct ObjectResult *) 0 ;
  Object *arg2 = (Object *) 0 ;
  
  arg1 = (struct ObjectResult *)jarg1; 
  arg2 = (Object *)jarg2; 
  if (arg1) (arg1)->object = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_ObjectResult_object__get___(void * jarg1) {
  void * jresult ;
  struct ObjectResult *arg1 = (struct ObjectResult *) 0 ;
  Object *result = 0 ;
  
  arg1 = (struct ObjectResult *)jarg1; 
  result = (Object *) ((arg1)->object);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_ObjectResult_error_set___(void * jarg1, void * jarg2) {
  struct ObjectResult *arg1 = (struct ObjectResult *) 0 ;
  Error *arg2 = (Error *) 0 ;
  
  arg1 = (struct ObjectResult *)jarg1; 
  arg2 = (Error *)jarg2; 
  if (arg1) (arg1)->error = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_ObjectResult_error_get___(void * jarg1) {
  void * jresult ;
  struct ObjectResult *arg1 = (struct ObjectResult *) 0 ;
  Error *result = 0 ;
  
  arg1 = (struct ObjectResult *)jarg1; 
  result = (Error *) ((arg1)->error);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_ObjectResult___() {
  void * jresult ;
  struct ObjectResult *result = 0 ;
  
  result = (struct ObjectResult *)calloc(1, sizeof(struct ObjectResult));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_ObjectResult___(void * jarg1) {
  struct ObjectResult *arg1 = (struct ObjectResult *) 0 ;
  
  arg1 = (struct ObjectResult *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_UploadResult_upload_set___(void * jarg1, void * jarg2) {
  struct UploadResult *arg1 = (struct UploadResult *) 0 ;
  Upload *arg2 = (Upload *) 0 ;
  
  arg1 = (struct UploadResult *)jarg1; 
  arg2 = (Upload *)jarg2; 
  if (arg1) (arg1)->upload = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_UploadResult_upload_get___(void * jarg1) {
  void * jresult ;
  struct UploadResult *arg1 = (struct UploadResult *) 0 ;
  Upload *result = 0 ;
  
  arg1 = (struct UploadResult *)jarg1; 
  result = (Upload *) ((arg1)->upload);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_UploadResult_error_set___(void * jarg1, void * jarg2) {
  struct UploadResult *arg1 = (struct UploadResult *) 0 ;
  Error *arg2 = (Error *) 0 ;
  
  arg1 = (struct UploadResult *)jarg1; 
  arg2 = (Error *)jarg2; 
  if (arg1) (arg1)->error = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_UploadResult_error_get___(void * jarg1) {
  void * jresult ;
  struct UploadResult *arg1 = (struct UploadResult *) 0 ;
  Error *result = 0 ;
  
  arg1 = (struct UploadResult *)jarg1; 
  result = (Error *) ((arg1)->error);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_UploadResult___() {
  void * jresult ;
  struct UploadResult *result = 0 ;
  
  result = (struct UploadResult *)calloc(1, sizeof(struct UploadResult));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_UploadResult___(void * jarg1) {
  struct UploadResult *arg1 = (struct UploadResult *) 0 ;
  
  arg1 = (struct UploadResult *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_DownloadResult_download_set___(void * jarg1, void * jarg2) {
  struct DownloadResult *arg1 = (struct DownloadResult *) 0 ;
  Download *arg2 = (Download *) 0 ;
  
  arg1 = (struct DownloadResult *)jarg1; 
  arg2 = (Download *)jarg2; 
  if (arg1) (arg1)->download = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_DownloadResult_download_get___(void * jarg1) {
  void * jresult ;
  struct DownloadResult *arg1 = (struct DownloadResult *) 0 ;
  Download *result = 0 ;
  
  arg1 = (struct DownloadResult *)jarg1; 
  result = (Download *) ((arg1)->download);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_DownloadResult_error_set___(void * jarg1, void * jarg2) {
  struct DownloadResult *arg1 = (struct DownloadResult *) 0 ;
  Error *arg2 = (Error *) 0 ;
  
  arg1 = (struct DownloadResult *)jarg1; 
  arg2 = (Error *)jarg2; 
  if (arg1) (arg1)->error = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_DownloadResult_error_get___(void * jarg1) {
  void * jresult ;
  struct DownloadResult *arg1 = (struct DownloadResult *) 0 ;
  Error *result = 0 ;
  
  arg1 = (struct DownloadResult *)jarg1; 
  result = (Error *) ((arg1)->error);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_DownloadResult___() {
  void * jresult ;
  struct DownloadResult *result = 0 ;
  
  result = (struct DownloadResult *)calloc(1, sizeof(struct DownloadResult));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_DownloadResult___(void * jarg1) {
  struct DownloadResult *arg1 = (struct DownloadResult *) 0 ;
  
  arg1 = (struct DownloadResult *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_WriteResult_bytes_written_set___(void * jarg1, unsigned long jarg2) {
  struct WriteResult *arg1 = (struct WriteResult *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct WriteResult *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->bytes_written = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_uplinkfSWIG_WriteResult_bytes_written_get___(void * jarg1) {
  unsigned long jresult ;
  struct WriteResult *arg1 = (struct WriteResult *) 0 ;
  size_t result;
  
  arg1 = (struct WriteResult *)jarg1; 
  result =  ((arg1)->bytes_written);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_WriteResult_error_set___(void * jarg1, void * jarg2) {
  struct WriteResult *arg1 = (struct WriteResult *) 0 ;
  Error *arg2 = (Error *) 0 ;
  
  arg1 = (struct WriteResult *)jarg1; 
  arg2 = (Error *)jarg2; 
  if (arg1) (arg1)->error = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_WriteResult_error_get___(void * jarg1) {
  void * jresult ;
  struct WriteResult *arg1 = (struct WriteResult *) 0 ;
  Error *result = 0 ;
  
  arg1 = (struct WriteResult *)jarg1; 
  result = (Error *) ((arg1)->error);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_WriteResult___() {
  void * jresult ;
  struct WriteResult *result = 0 ;
  
  result = (struct WriteResult *)calloc(1, sizeof(struct WriteResult));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_WriteResult___(void * jarg1) {
  struct WriteResult *arg1 = (struct WriteResult *) 0 ;
  
  arg1 = (struct WriteResult *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_ReadResult_bytes_read_set___(void * jarg1, unsigned long jarg2) {
  struct ReadResult *arg1 = (struct ReadResult *) 0 ;
  size_t arg2 ;
  
  arg1 = (struct ReadResult *)jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->bytes_read = arg2;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_uplinkfSWIG_ReadResult_bytes_read_get___(void * jarg1) {
  unsigned long jresult ;
  struct ReadResult *arg1 = (struct ReadResult *) 0 ;
  size_t result;
  
  arg1 = (struct ReadResult *)jarg1; 
  result =  ((arg1)->bytes_read);
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_ReadResult_error_set___(void * jarg1, void * jarg2) {
  struct ReadResult *arg1 = (struct ReadResult *) 0 ;
  Error *arg2 = (Error *) 0 ;
  
  arg1 = (struct ReadResult *)jarg1; 
  arg2 = (Error *)jarg2; 
  if (arg1) (arg1)->error = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_ReadResult_error_get___(void * jarg1) {
  void * jresult ;
  struct ReadResult *arg1 = (struct ReadResult *) 0 ;
  Error *result = 0 ;
  
  arg1 = (struct ReadResult *)jarg1; 
  result = (Error *) ((arg1)->error);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_ReadResult___() {
  void * jresult ;
  struct ReadResult *result = 0 ;
  
  result = (struct ReadResult *)calloc(1, sizeof(struct ReadResult));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_ReadResult___(void * jarg1) {
  struct ReadResult *arg1 = (struct ReadResult *) 0 ;
  
  arg1 = (struct ReadResult *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_StringResult_string__set___(void * jarg1, char * jarg2) {
  struct StringResult *arg1 = (struct StringResult *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (struct StringResult *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    free(arg1->string);
    if (arg2) {
      arg1->string = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->string, (const char *)arg2);
    } else {
      arg1->string = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_StringResult_string__get___(void * jarg1) {
  char * jresult ;
  struct StringResult *arg1 = (struct StringResult *) 0 ;
  char *result = 0 ;
  
  arg1 = (struct StringResult *)jarg1; 
  result = (char *) ((arg1)->string);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_StringResult_error_set___(void * jarg1, void * jarg2) {
  struct StringResult *arg1 = (struct StringResult *) 0 ;
  Error *arg2 = (Error *) 0 ;
  
  arg1 = (struct StringResult *)jarg1; 
  arg2 = (Error *)jarg2; 
  if (arg1) (arg1)->error = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_StringResult_error_get___(void * jarg1) {
  void * jresult ;
  struct StringResult *arg1 = (struct StringResult *) 0 ;
  Error *result = 0 ;
  
  arg1 = (struct StringResult *)jarg1; 
  result = (Error *) ((arg1)->error);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_uplinkfSWIG_new_StringResult___() {
  void * jresult ;
  struct StringResult *result = 0 ;
  
  result = (struct StringResult *)calloc(1, sizeof(struct StringResult));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_uplinkfSWIG_delete_StringResult___(void * jarg1) {
  struct StringResult *arg1 = (struct StringResult *) 0 ;
  
  arg1 = (struct StringResult *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT char * SWIGSTDCALL CSharp_uplinkfSWIG_get_storj_version___() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)get_storj_version();
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


#ifdef __cplusplus
}
#endif

